# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotoDraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_number', models.PositiveIntegerField(unique=True)),
                ('date', models.DateField()),
                ('number_1', models.PositiveSmallIntegerField()),
                ('number_2', models.PositiveSmallIntegerField()),
                ('number_3', models.PositiveSmallIntegerField()),
                ('number_4', models.PositiveSmallIntegerField()),
                ('number_5', models.PositiveSmallIntegerField()),
                ('number_6', models.PositiveSmallIntegerField()),
                ('number_7', models.PositiveSmallIntegerField()),
                ('number_8', models.PositiveSmallIntegerField()),
                ('number_9', models.PositiveSmallIntegerField()),
                ('number_10', models.PositiveSmallIntegerField()),
                ('number_11', models.PositiveSmallIntegerField()),
                ('number_12', models.PositiveSmallIntegerField()),
                ('number_13', models.PositiveSmallIntegerField()),
                ('number_14', models.PositiveSmallIntegerField()),
                ('number_15', models.PositiveSmallIntegerField()),
                ('total_collected', models.DecimalField(decimal_places=2, max_digits=19)),
                ('total_winners', models.PositiveIntegerField()),
                ('prize_per_winner', models.DecimalField(decimal_places=2, max_digits=19)),
                ('prize_for_next_draw', models.DecimalField(decimal_places=2, max_digits=19)),
                ('winning_cities', models.ManyToManyField(to='states.City')),
            ],
        ),
    ]
