# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotoDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_marker', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('count_number_1', models.PositiveIntegerField()),
                ('count_number_2', models.PositiveIntegerField()),
                ('count_number_3', models.PositiveIntegerField()),
                ('count_number_4', models.PositiveIntegerField()),
                ('count_number_5', models.PositiveIntegerField()),
                ('count_number_6', models.PositiveIntegerField()),
                ('count_number_7', models.PositiveIntegerField()),
                ('count_number_8', models.PositiveIntegerField()),
                ('count_number_9', models.PositiveIntegerField()),
                ('count_number_10', models.PositiveIntegerField()),
                ('count_number_11', models.PositiveIntegerField()),
                ('count_number_12', models.PositiveIntegerField()),
                ('count_number_13', models.PositiveIntegerField()),
                ('count_number_14', models.PositiveIntegerField()),
                ('count_number_15', models.PositiveIntegerField()),
                ('count_number_16', models.PositiveIntegerField()),
                ('count_number_17', models.PositiveIntegerField()),
                ('count_number_18', models.PositiveIntegerField()),
                ('count_number_19', models.PositiveIntegerField()),
                ('count_number_20', models.PositiveIntegerField()),
                ('count_number_21', models.PositiveIntegerField()),
                ('count_number_22', models.PositiveIntegerField()),
                ('count_number_23', models.PositiveIntegerField()),
                ('count_number_24', models.PositiveIntegerField()),
                ('count_number_25', models.PositiveIntegerField()),
            ],
        ),
    ]
